version: 2
jobs:
  install_ansible_roles:
    docker:
      - image: williamyeh/ansible:alpine3
    steps:
      - checkout
      - run:
          name: Install Ansible dependencies
          command: apk add --no-cache git
      - run:
          name: Download Ansible dependencies
          command: make roles
      - persist_to_workspace:
          root: .
          paths:
            - ./*

  validate_packer:
    docker:
      - image: hashicorp/packer:light
    steps:
      - checkout
      - run:
          name: Validate Packer templates
          command: make validate_packer

  deploy_images:
    docker:
      - image: 18fgsa/devsecops-builder:alpine
    steps:
      - attach_workspace:
          at: .

      - add_ssh_keys
      - run:
          name: Disable host key checking
          command: printf "\nHost *\n\tStrictHostKeyChecking no" >> ~/.ssh/config

      - run:
          name: Build rhel7 AMI
          command: |
            export USER=$(whoami)
            make rhel7

      - run:
          name: Build ubuntu16 AMI
          command: |
            export USER=$(whoami)
            make ubuntu16

workflows:
  version: 2

  validate_and_deploy:
    jobs:
      - install_ansible_roles
      - validate_packer
      - deploy_images:
          filters:
            branches:
              only:
                - master
          requires:
            - install_ansible_roles
            - validate_packer
